---
- name: build a Jenkins Service
  hosts: test_vagrant
  sudo: true
  remote_user: vagrant
  tasks: 
    - name: Copy project war
      copy:
        src: target/java-jsp-jdbc-mysql-template.war
        dest: /var/lib/tomcat7/webapps